EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','account_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','money_account_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','money_dominion_storage_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','collection_item_account_complate_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','collection_item_account_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','pet_deck_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','pet_equip_item_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','item_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','item_option_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','dungeon_ticket_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','cash_bag_character_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','buff_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','mastery_step_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','mastery_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','great_building_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','mail_event_reward_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','dungeon_clear_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','collection_item_character_complate_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','collection_item_character_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','equip_vehicle_ride_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','vehicle_ride_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','event_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','block_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','pet_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','character_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','character_delete_reserve_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','character_delete_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','character_revival_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','force_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','force_blood_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','achievement_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','productbuycnt_character_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','money_character_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','battle_pass_reward_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','equip_costumehide_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','equip_item_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','battle_pass_mission_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','costume_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','skill_active_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','customize_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','customtitle_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','skill_deck_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','quest_sub_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','quickslot_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','quest_daily_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','playdata_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','quest_main_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','item_holdoption_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','battle_pass_info_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','quest_relation_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','quest_request_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','tutorialclear_character_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','quest_relation_reward_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','gameoption_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','fame_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','timeticket_character_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','eventdata_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','waypoint_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','quest_sub_clearcnt_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','equip_costume_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','quest_daily_list_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','compose_fail_point_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','period_goods_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','gacha_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','closed_training_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','character_server_expedition_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','character_server_expedition_native_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','limit_drop_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','character_phase_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','item_subcooltime_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','collection_siege_reg_time_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','character_nft_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','item_acquisition_path_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','ads_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','draco_smelting_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','equip_luxury_costume_hide_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','equip_luxury_costume_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','benediction_event_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','proud_wonder_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','holy_stuff_grade_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','holy_stuff_slot_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','guild_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','guild_supply_unlock_time',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','guild_shop_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','guild_option_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','guild_npc_shop_income_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','guild_member_donation_weekly_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','guild_member_donation_daily_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','guild_member_authority_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','guild_name_change_reserve_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','guild_joinrequest_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','guild_joininvite_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','guild_gift_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','guild_expedition_create_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','guild_exedition_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','guild_develop_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','guild_command_mark_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','character_guild_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','character_guild_donation_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','money_guild_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','unsealing_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','unsealing_support_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','quest_guild_list_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','friend_request_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','friend_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','pk_history',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','pk_wanted',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','sickness_recovery_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','mail_character_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','mail_character_itemidx_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','mail_character_money_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','character_guild_expedition_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','character_guild_receive_cost',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','trade_log_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','trade_register_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','potential_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','guild_coop_mission_group_complete_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','guild_coop_mission_group_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','guild_coop_mission_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','quest_cooperation_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','cash_bag_character_gift_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','character_death_penalty_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','character_death_penalty_item_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','painting_guild_trade_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','black_dragon_dungeon_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','character_conquer_server_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','shop_random_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','shop_randomlist_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','item_make_agency_character_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','item_lv_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','magic_orb_deck_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','symbol_deck_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','shop_limit_character_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','collection_book_character_complate_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','popup_store_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','event_bingo_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','dragon_gear_bless_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','pray_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','item_passive_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','scripturehall_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','scripturehall_item_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','item_hold_passive_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','item_holdoption_special_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','battle_pass_check_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','productbuycnt_account_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','force_slump_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','character_server_change_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','item_make_xdraco_limit_character_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','heaven_training_group_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','heaven_training_node_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','heaven_training_option_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','divine_dragon_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','contents_option_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','mission_data_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','mission_pass_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','cash_shop_buy_item',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','heaven_training_support_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','guild_point_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','guild_history_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','guild_history_money_tb',1
EXEC [dbo].[UP_COPY_TABLE] N'{{LINKED_SERVER}}','dbo','guild_history_param_tb',1
