# Generated by Django 4.2.18 on 2026-09-10 17:08

from django.db import migrations


def rename_server_merge_permission(apps, schema_editor):
    """权限名称改为英文，Django 的 create_permissions 不会更新已存在权限的名称"""
    Permission = apps.get_model("auth", "Permission")
    Permission.objects.filter(codename="menu_server_merge").update(
        name="菜单 ServerMerge"
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0002_server_merge'),
    ]

    operations = [
        migrations.RunPython(rename_server_merge_permission, noop),
        migrations.AlterModelOptions(
            name='permission',
            options={'managed': True, 'permissions': (('menu_dashboard', '菜单 Dashboard'), ('menu_sqlcheck', '菜单 SQL审核'), ('menu_sqlworkflow', '菜单 SQL上线'), ('menu_sqlanalyze', '菜单 SQL分析'), ('menu_query', '菜单 SQL查询'), ('menu_sqlquery', '菜单 在线查询'), ('menu_queryapplylist', '菜单 权限管理'), ('menu_sqloptimize', '菜单 SQL优化'), ('menu_sqladvisor', '菜单 优化工具'), ('menu_slowquery', '菜单 慢查日志'), ('menu_instance', '菜单 实例管理'), ('menu_instance_list', '菜单 实例列表'), ('menu_dbdiagnostic', '菜单 会话管理'), ('menu_database', '菜单 数据库管理'), ('menu_instance_account', '菜单 实例账号管理'), ('menu_param', '菜单 参数配置'), ('menu_param_compare', '菜单 参数对比'), ('menu_data_dictionary', '菜单 数据字典'), ('menu_tools', '菜单 工具插件'), ('menu_archive', '菜单 数据归档'), ('menu_my2sql', '菜单 My2SQL'), ('menu_schemasync', '菜单 SchemaSync'), ('menu_mssql_log_rollback', '菜单 MSSQL2SQL'), ('menu_server_merge', '菜单 ServerMerge'), ('menu_system', '菜单 系统管理'), ('menu_document', '菜单 相关文档'), ('menu_openapi', '菜单 OpenAPI'), ('sql_submit', '提交SQL上线工单'), ('sql_review', '审核SQL上线工单'), ('sql_execute_for_resource_group', '执行SQL上线工单(资源组粒度)'), ('sql_execute', '执行SQL上线工单(仅自己提交的)'), ('sql_analyze', '执行SQL分析'), ('optimize_sqladvisor', '执行SQLAdvisor'), ('optimize_sqltuning', '执行SQLTuning'), ('optimize_soar', '执行SOAR'), ('query_applypriv', '申请查询权限'), ('query_mgtpriv', '管理查询权限'), ('query_review', '审核查询权限'), ('query_submit', '提交SQL查询'), ('query_all_instances', '可查询所有实例'), ('query_resource_group_instance', '可查询所在资源组内的所有实例'), ('process_view', '查看会话'), ('process_kill', '终止会话'), ('tablespace_view', '查看表空间'), ('trx_view', '查看事务信息'), ('trxandlocks_view', '查看锁信息'), ('instance_account_manage', '管理实例账号'), ('param_view', '查看实例参数列表'), ('param_edit', '修改实例参数'), ('data_dictionary_export', '导出数据字典'), ('archive_apply', '提交归档申请'), ('archive_review', '审核归档申请'), ('archive_mgt', '管理归档申请'), ('audit_user', '审计权限'), ('query_download', '在线查询下载权限'), ('offline_download', '离线下载权限'), ('menu_sqlexportworkflow', '菜单 数据导出'), ('sqlexport_submit', '提交数据导出'))},
        ),
    ]
