# Generated by Django 4.2.18 on 2026-09-10 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerMergeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='任务名称')),
                ('target_instance_name', models.CharField(max_length=50, verbose_name='目标实例')),
                ('source_instance_name', models.CharField(max_length=50, verbose_name='源实例')),
                ('variables', models.TextField(blank=True, default='', verbose_name='合服变量JSON')),
                ('config', models.TextField(blank=True, default='', verbose_name='模块库配置JSON')),
                ('create_user', models.CharField(blank=True, default='', max_length=30, verbose_name='创建人')),
                ('create_user_display', models.CharField(blank=True, default='', max_length=50, verbose_name='创建人中文名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '合服任务',
                'verbose_name_plural': '合服任务',
                'db_table': 'server_merge_task',
                'ordering': ['-id'],
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'managed': True, 'permissions': (('menu_dashboard', '菜单 Dashboard'), ('menu_sqlcheck', '菜单 SQL审核'), ('menu_sqlworkflow', '菜单 SQL上线'), ('menu_sqlanalyze', '菜单 SQL分析'), ('menu_query', '菜单 SQL查询'), ('menu_sqlquery', '菜单 在线查询'), ('menu_queryapplylist', '菜单 权限管理'), ('menu_sqloptimize', '菜单 SQL优化'), ('menu_sqladvisor', '菜单 优化工具'), ('menu_slowquery', '菜单 慢查日志'), ('menu_instance', '菜单 实例管理'), ('menu_instance_list', '菜单 实例列表'), ('menu_dbdiagnostic', '菜单 会话管理'), ('menu_database', '菜单 数据库管理'), ('menu_instance_account', '菜单 实例账号管理'), ('menu_param', '菜单 参数配置'), ('menu_param_compare', '菜单 参数对比'), ('menu_data_dictionary', '菜单 数据字典'), ('menu_tools', '菜单 工具插件'), ('menu_archive', '菜单 数据归档'), ('menu_my2sql', '菜单 My2SQL'), ('menu_schemasync', '菜单 SchemaSync'), ('menu_mssql_log_rollback', '菜单 MSSQL2SQL'), ('menu_server_merge', '菜单 合服管理'), ('menu_system', '菜单 系统管理'), ('menu_document', '菜单 相关文档'), ('menu_openapi', '菜单 OpenAPI'), ('sql_submit', '提交SQL上线工单'), ('sql_review', '审核SQL上线工单'), ('sql_execute_for_resource_group', '执行SQL上线工单(资源组粒度)'), ('sql_execute', '执行SQL上线工单(仅自己提交的)'), ('sql_analyze', '执行SQL分析'), ('optimize_sqladvisor', '执行SQLAdvisor'), ('optimize_sqltuning', '执行SQLTuning'), ('optimize_soar', '执行SOAR'), ('query_applypriv', '申请查询权限'), ('query_mgtpriv', '管理查询权限'), ('query_review', '审核查询权限'), ('query_submit', '提交SQL查询'), ('query_all_instances', '可查询所有实例'), ('query_resource_group_instance', '可查询所在资源组内的所有实例'), ('process_view', '查看会话'), ('process_kill', '终止会话'), ('tablespace_view', '查看表空间'), ('trx_view', '查看事务信息'), ('trxandlocks_view', '查看锁信息'), ('instance_account_manage', '管理实例账号'), ('param_view', '查看实例参数列表'), ('param_edit', '修改实例参数'), ('data_dictionary_export', '导出数据字典'), ('archive_apply', '提交归档申请'), ('archive_review', '审核归档申请'), ('archive_mgt', '管理归档申请'), ('audit_user', '审计权限'), ('query_download', '在线查询下载权限'), ('offline_download', '离线下载权限'), ('menu_sqlexportworkflow', '菜单 数据导出'), ('sqlexport_submit', '提交数据导出'))},
        ),
        migrations.CreateModel(
            name='ServerMergeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(choices=[(2, '2-创建外部数据源和存储过程'), (3, '3-复制和清理(Pre_work/Copy/Delete)'), (4, '4-数据写入(Insert)'), (5, '5-后处理(Post_work)')], verbose_name='步骤')),
                ('module', models.CharField(choices=[('common', '通用'), ('game', 'GAME'), ('front', 'FRONT'), ('index', 'INDEX')], max_length=20, verbose_name='模块')),
                ('seq', models.IntegerField(default=1, verbose_name='同一步骤内的顺序')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
                ('sql', models.TextField(verbose_name='SQL 语句')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('use_transaction', models.BooleanField(default=True, verbose_name='使用事务执行')),
                ('update_user', models.CharField(blank=True, default='', max_length=30, verbose_name='最后修改人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '合服默认SQL模板',
                'verbose_name_plural': '合服默认SQL模板',
                'db_table': 'server_merge_template',
                'managed': True,
                'unique_together': {('step', 'module', 'seq')},
            },
        ),
        migrations.CreateModel(
            name='ServerMergeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(verbose_name='步骤')),
                ('module', models.CharField(blank=True, default='', max_length=20, verbose_name='模块')),
                ('seq', models.IntegerField(default=1, verbose_name='顺序')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
                ('run_db', models.CharField(blank=True, default='', max_length=64, verbose_name='执行库')),
                ('use_transaction', models.BooleanField(default=True, verbose_name='使用事务')),
                ('sql_text', models.TextField(blank=True, default='', verbose_name='执行的SQL')),
                ('status', models.CharField(default='running', max_length=20, verbose_name='状态')),
                ('affected_rows', models.IntegerField(default=0, verbose_name='影响行数')),
                ('cost_time', models.FloatField(default=0, verbose_name='耗时(秒)')),
                ('error_info', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('user_name', models.CharField(blank=True, default='', max_length=30, verbose_name='执行人')),
                ('user_display', models.CharField(blank=True, default='', max_length=50, verbose_name='执行人中文名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sql.servermergetask', verbose_name='合服任务')),
            ],
            options={
                'verbose_name': '合服执行记录',
                'verbose_name_plural': '合服执行记录',
                'db_table': 'server_merge_log',
                'ordering': ['-id'],
                'managed': True,
            },
        ),
    ]
