# Generated by Django 4.2.18 on 2026-09-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0003_server_merge_permission_rename'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerMergeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='方案名称')),
                ('target_instance_name', models.CharField(max_length=50, verbose_name='目标实例')),
                ('source_instance_name', models.CharField(max_length=50, verbose_name='源实例')),
                ('index_db', models.CharField(blank=True, default='', max_length=64, verbose_name='INDEX库')),
                ('modules', models.TextField(blank=True, default='', verbose_name='模块库配置JSON')),
                ('items', models.TextField(blank=True, default='', verbose_name='步骤SQL配置JSON')),
                ('create_user', models.CharField(blank=True, default='', max_length=30, verbose_name='创建人')),
                ('create_user_display', models.CharField(blank=True, default='', max_length=50, verbose_name='创建人中文名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '合服方案',
                'verbose_name_plural': '合服方案',
                'db_table': 'server_merge_profile',
                'ordering': ['-update_time'],
                'managed': True,
                'unique_together': {('name', 'create_user')},
            },
        ),
    ]
